#!/bin/bash

# You can pass test project directory as argument
TEST_PROJECT=$1

# Or have it auto-detect the test project
if [[ -z "$TEST_PROJECT" ]]; then
    TEST_PROJECT=$(ls -1 | rg '.*[Tt]ests')
fi

if [[ -z "$TEST_PROJECT" ]]; then
    echo 'Could not auto-detect tests project; please provide as an argument.'
    exit 1
fi

# Find the most recent test run
TESTRUN_ID=$(ls -1t "$TEST_PROJECT/TestResults" | head -n 1)

if [[ -z "$TESTRUN_ID" ]]; then
    echo 'Could not find a test run; have you run unit tests with --collect:"XPlat Code Coverage"?'
    exit 2
fi

COVERAGE_PATH="$TEST_PROJECT/TestResults/$TESTRUN_ID/coverage.cobertura.xml"

# Generate coverage report
reportgenerator -reports:$COVERAGE_PATH -targetdir:"coveragereport" -reporttypes:Html

echo "Coverage report generated."
echo "Open it with:"
echo "    open coveragereport/index.html"
